backend:
  name: github
  repo: msieurmoustache/gaabp

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: app/src/markdown-pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: formation
    label: Formation
    folder: app/src/markdown-pages/formation
    create: true
    fields:
      - { name: path, label: Path }
      - { name: niveau, label: Niveau, widget: select,  options: ["BC0", "BC1", "BC2", "BC3", "FR0", "Coeducation"] }
      - { name: branche, label: Branche, widget: select,  options: ["Bleue", "Jaune", "Verte", "Rouge", "Multibranche"] }
      - { name: title, label: Title }
      - { name: externalLink, label: Lien vers contenu externe}
      - { name: body, label: Body, widget: markdown }