const Formations = [
  {
    id: "1",
    alias: "C-E-P-1-Camp-ecole-preparatoire-1",
    name: "C.E.P. 1  (Camp-\u00e9cole pr\u00e9paratoire 1)",
  },
  {
    id: "2",
    alias: "C-E-P-2-Camp-ecole-preparatoire-2",
    name: "C.E.P. 2  (Camp-\u00e9cole pr\u00e9paratoire 2)",
  },
  {
    id: "3",
    alias: "C-E-P-3-Camp-ecole-preparatoire-3",
    name: "C.E.P. 3  (Camp-\u00e9cole pr\u00e9paratoire 3)",
  },
  {
    id: "4",
    alias: "Badge-de-bois-2-Buchettes",
    name: "Badge de bois / 2 Buchettes",
  },
  {
    id: "5",
    alias: "A-D-C-C-Assistant-deputy-camp-chef-3-Buchettes",
    name: "A.D.C.C. (Assistant deputy camp chef) / 3 Buchettes",
  },
  {
    id: "6",
    alias: "D-C-C-Deputy-camp-chef-4-Buchettes",
    name: "D.C.C. (Deputy camp chef) / 4 Buchettes",
  },
  { id: "7", alias: "BC1", name: "BC1" },
  { id: "8", alias: "BC2", name: "BC2" },
  { id: "9", alias: "BC3", name: "BC3" },
  { id: "10", alias: "Multibranche", name: "Multibranche" },
  { id: "11", alias: "Lynx-Argent", name: "Lynx Argent" },
  { id: "12", alias: "Lynx-Or", name: "Lynx Or" },
  { id: "13", alias: "Lynx-Or-Etoile", name: "Lynx Or \u00c9toil\u00e9" },
  { id: "14", alias: "FR1", name: "FR1" },
  { id: "15", alias: "FR2", name: "FR2" },
  { id: "16", alias: "Secourisme", name: "Secourisme" },
  { id: "18", alias: "Goeland-Or", name: "Go\u00e9land Or" },
  { id: "19", alias: "Goeland-Argent", name: "Go\u00e9land Argent" },
  { id: "20", alias: "Goeland-Bronze", name: "Go\u00e9land Bronze" },
  { id: "21", alias: "Hirondelle", name: "Hirondelle" },
  { id: "22", alias: "Faucon-Or", name: "Faucon Or" },
  { id: "23", alias: "Faucon-Argent", name: "Faucon Argent" },
  { id: "24", alias: "Faucon-Bronze", name: "Faucon Bronze" },
  { id: "25", alias: "Epervier", name: "\u00c9pervier" },
  { id: "30", alias: "Apprenti-Formateur", name: "Apprenti Formateur" },
  { id: "32", alias: "Formation-Formateur", name: "Formation Formateur" },
  {
    id: "34",
    alias: "Formation-Formateur-Conseiller",
    name: "Formation Formateur Conseiller",
  },
  {
    id: "35",
    alias: "Formation-externe-a-l-association",
    name: "Formation externe \u00e0 l'association",
  },
  { id: "36", alias: "Autres", name: "Autres" },
  { id: "37", alias: "", name: "-" },
  { id: "38", alias: "Formation-Harfang-1", name: "Formation Harfang 1" },
  { id: "39", alias: "bc0", name: "BC0" },
  { id: "40", alias: "fr0", name: "FR0" },
];

export default Formations;
